script: ./.travis/build
language: cpp
before_install:
- git submodule update --init --recursive
- sudo apt-get update -qq
- sudo apt-get install -qq doxygen doxygen-latex libboost-all-dev libltdl-dev liblog4cxx10-dev  liblapack-dev libblas-dev gfortran python-dev python-sphinx python-numpy
- sudo pip install cpp-coveralls --use-mirrors
compiler:
- clang
- gcc
env:
  global:
    secure: luYfLgyF6V0tYlu5sCy0WRX+SnvrMz4FxbmPTJwhxPDIYo3oTP3Cj1L9O/BA5tKj3dbRVo5yt2JhKnnDzxhXoGrS0YV20Ck8rd/i3t1eUjPy1ia0npKt6om4Oj6httnwjNXcHy7qmn4AjUH0CrI1pP6HueEPMtiQ5m2xtEF3iAo=
notifications:
  email:
  - hpp-source@laas.fr
after_success:
- coveralls -e _travis/install -e tests
- git config --global user.name "Travis CI"
- git config --global user.email "thomas.moulard+travis@gmail.com"
- git remote set-url origin https://thomas-moulard:${GH_TOKEN}@github.com/stack-of-tasks/sot-motion-planner.git
- git fetch origin gh-pages:gh-pages
- cd _travis/build/doc && ../../../cmake/github/update-doxygen-doc.sh
matrix:
  allow_failures:
  - compiler: clang
branches:
  only:
  - master
